import { QueryInterface, DataTypes } from "sequelize";
import { v4 as uuidv4 } from "uuid";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
    await queryInterface.bulkInsert(
      "Permissions",
      [
        {
          id: uuidv4(),
          name: "Add",
          slug: "add",
          navParentId: "9a4bfd18-a022-4c8f-90e7-288e9b8880b8",
          url: "create-account",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View",
          slug: "view-all",
          navParentId: "9a4bfd18-a022-4c8f-90e7-288e9b8880b8",
          url: "get-accountbook",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Add",
          slug: "add-customer",
          navParentId: "e837484c-713a-4526-bb9e-8a8434c82828",
          url: "reg-customer",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View",
          slug: "view-customers",
          navParentId: "e837484c-713a-4526-bb9e-8a8434c82828",
          url: "get-customers",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Ledger",
          slug: "customer-ledger",
          navParentId: "e837484c-713a-4526-bb9e-8a8434c82828",
          url: "search-customer-for-ledger",
          orderIndex: 3,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Place Order",
          slug: "place-order",
          navParentId: "e837484c-713a-4526-bb9e-8a8434c82828",
          url: "raise-customer-order",
          orderIndex: 4,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Orders",
          slug: "order",
          navParentId: "e837484c-713a-4526-bb9e-8a8434c82828",
          url: "get-all-orders",
          orderIndex: 5,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit",
          slug: "edit",
          navParentId: "e837484c-713a-4526-bb9e-8a8434c82828",
          url: "edit-customer",
          orderIndex: 6,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Add",
          slug: "add-supplier",
          navParentId: "473863ff-7878-441d-a165-48c841587c6a",
          url: "reg-supplier",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View All",
          slug: "view-suppliers",
          navParentId: "473863ff-7878-441d-a165-48c841587c6a",
          url: "get-suppliers",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Ledger",
          slug: "supplier-ledger",
          navParentId: "473863ff-7878-441d-a165-48c841587c6a",
          url: "get-all-supplier-ledger",
          orderIndex: 3,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Received Order",
          slug: "place-supplier-order",
          navParentId: "473863ff-7878-441d-a165-48c841587c6a",
          url: "raise-supplier-order",
          orderIndex: 4,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Orders",
          slug: "view-order",
          navParentId: "473863ff-7878-441d-a165-48c841587c6a",
          url: "get-all-supplier-orders",
          orderIndex: 5,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit Supplier",
          slug: "edit-supplier",
          navParentId: "473863ff-7878-441d-a165-48c841587c6a",
          url: "edit-supplier",
          orderIndex: 6,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Add",
          slug: "add-product",
          navParentId: "453352ee-9a63-430d-8aee-0aed98e5d800",
          url: "add-product",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View All",
          slug: "view-products",
          navParentId: "453352ee-9a63-430d-8aee-0aed98e5d800",
          url: "get-products",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Create",
          slug: "create-pharmacy-store",
          navParentId: "d1b33b66-f41a-4765-b628-d08735be7192",
          url: "create-pharmstore",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View All",
          slug: "view-pharmacy",
          navParentId: "d1b33b66-f41a-4765-b628-d08735be7192",
          url: "view-pharmstore-prod",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Place Order",
          slug: "place-pharmacy-order",
          navParentId: "d1b33b66-f41a-4765-b628-d08735be7192",
          url: "raise-pharm-order",
          orderIndex: 3,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Orders",
          slug: "view-pharmacy-order",
          navParentId: "d1b33b66-f41a-4765-b628-d08735be7192",
          url: "view-pharm-order",
          orderIndex: 4,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit Store",
          slug: "edit-pharmacy",
          navParentId: "d1b33b66-f41a-4765-b628-d08735be7192",
          url: "edit-pharmstore",
          orderIndex: 5,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Delete Store",
          slug: "delete-pharmacy-store",
          navParentId: "d1b33b66-f41a-4765-b628-d08735be7192",
          url: "delete-pharmstore",
          orderIndex: 6,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          id: uuidv4(),
          name: "Create Shelf",
          slug: "create-shelf",
          navParentId: "7c886cc6-aecb-42a7-939f-e2ba93101733",
          url: "create-gen-store",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Shelf",
          slug: "view-shelf",
          navParentId: "7c886cc6-aecb-42a7-939f-e2ba93101733",
          url: "view-gen-store",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Place Order",
          slug: "raise-general-order",
          navParentId: "7c886cc6-aecb-42a7-939f-e2ba93101733",
          url: "create-genstore-order",
          orderIndex: 3,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Order",
          slug: "view-general-order",
          navParentId: "7c886cc6-aecb-42a7-939f-e2ba93101733",
          url: "view-gen-order",
          orderIndex: 4,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit shelf",
          slug: "edit-general-store",
          navParentId: "7c886cc6-aecb-42a7-939f-e2ba93101733",
          url: "edit-genstore",
          orderIndex: 5,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Delete Shelf",
          slug: "delete-shelf",
          navParentId: "7c886cc6-aecb-42a7-939f-e2ba93101733",
          url: "delete-genstore",
          orderIndex: 6,
          isNav:false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Create",
          slug: "create-department-store",
          navParentId: "2fd84812-a648-4988-9062-1fe375fd74af",
          url: "create-dept-store",
          orderIndex: 1,
          isNav:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View All",
          slug: "department-store-products",
          navParentId: "2fd84812-a648-4988-9062-1fe375fd74af",
          url: "view-deptstore-prod",
          orderIndex: 2,
          isNav:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Raw materials",
          slug: "view-store-raw",
          navParentId: "2fd84812-a648-4988-9062-1fe375fd74af",
          url: "view-deptstore-raw",
          orderIndex: 3,
          isNav:false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Place Order",
          slug: "place-store-order",
          navParentId: "2fd84812-a648-4988-9062-1fe375fd74af",
          url: "create-deptstore-order",
          orderIndex: 4,
          isNav:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Orders",
          slug: "view-dept-orders",
          navParentId: "2fd84812-a648-4988-9062-1fe375fd74af",
          url: "view-deptstore-order",
          orderIndex: 5,
          isNav:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit Store",
          slug: "edit-dept-store",
          navParentId: "2fd84812-a648-4988-9062-1fe375fd74af",
          url: "edit-deptstore",
          orderIndex: 6,
          isNav:false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Delete Store",
          slug: "delete-dept-store",
          navParentId: "2fd84812-a648-4988-9062-1fe375fd74af",
          url: "delete-deptstore",
          orderIndex: 7,
          isNav:false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Delete Store",
          slug: "delete-dept-store",
          navParentId: "91b48a90-258e-4293-87c0-b2f609569801",
          url: "delete-deptstore",
          orderIndex: 1,
          isNav:false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface: QueryInterface) {
    await queryInterface.bulkDelete("Permissions", {}, {});
  },
};
