import { QueryInterface, DataTypes } from "sequelize";
import { v4 as uuidv4 } from "uuid";
import NavParent from "../models/navparent";

/** @type {import('sequelize-cli').Migration} */

module.exports = {
  async up(queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
    const navParents = await NavParent.findAll();

    if (!navParents || navParents.length === 0) {
      throw new Error("NavParent records are empty or not found!");
    }
    interface NavParentMap {
      [key: string]: string;
    }

    const navParentsMap: NavParentMap = navParents.reduce((acc, parent) => {
      const parentName = parent.dataValues.name;
      const parentId = parent.dataValues.id;
      acc[parentName] = parentId;
      return acc;
    }, {} as NavParentMap);
    await queryInterface.bulkInsert(
      "Permissions",
      [
        {
          id: uuidv4(),
          name: "Add",
          slug: "add",
          navParentId: navParentsMap["Account Book"],
          url: "create-account",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View",
          slug: "view-all",
          navParentId: navParentsMap["Account Book"],
          url: "get-accountbook",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Add",
          slug: "add-customer",
          navParentId: navParentsMap["Customers"],
          url: "reg-customer",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View",
          slug: "view-customers",
          navParentId: navParentsMap["Customers"],
          url: "get-customers",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Ledger",
          slug: "customer-ledger",
          navParentId: navParentsMap["Customers"],
          url: "search-customer-for-ledger",
          orderIndex: 3,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Place Order",
          slug: "place-order",
          navParentId: navParentsMap["Customers"],
          url: "raise-customer-order",
          orderIndex: 4,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Orders",
          slug: "order",
          navParentId: navParentsMap["Customers"],
          url: "get-all-orders",
          orderIndex: 5,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit",
          slug: "edit",
          navParentId: navParentsMap["Customers"],
          url: "edit-customer",
          orderIndex: 6,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Add",
          slug: "add-supplier",
          navParentId: navParentsMap["Suppliers"],
          url: "reg-supplier",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View All",
          slug: "view-suppliers",
          navParentId: navParentsMap["Suppliers"],
          url: "get-suppliers",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Ledger",
          slug: "supplier-ledger",
          navParentId: navParentsMap["Suppliers"],
          url: "get-all-supplier-ledger",
          orderIndex: 3,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Received Order",
          slug: "place-supplier-order",
          navParentId: navParentsMap["Suppliers"],
          url: "raise-supplier-order",
          orderIndex: 4,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Orders",
          slug: "view-order",
          navParentId: navParentsMap["Suppliers"],
          url: "get-all-supplier-orders",
          orderIndex: 5,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit Supplier",
          slug: "edit-supplier",
          navParentId: navParentsMap["Suppliers"],
          url: "edit-supplier",
          orderIndex: 6,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Add",
          slug: "add-product",
          navParentId: navParentsMap["Products"],
          url: "add-product",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View All",
          slug: "view-products",
          navParentId: navParentsMap["Products"],
          url: "get-products",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Create",
          slug: "create-pharmacy-store",
          navParentId: navParentsMap["Pharmacy Store"],
          url: "create-pharmstore",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View All",
          slug: "view-pharmacy",
          navParentId: navParentsMap["Pharmacy Store"],
          url: "view-pharmstore-prod",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Place Order",
          slug: "place-pharmacy-order",
          navParentId: navParentsMap["Pharmacy Store"],
          url: "raise-pharm-order",
          orderIndex: 3,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Orders",
          slug: "view-pharmacy-order",
          navParentId: navParentsMap["Pharmacy Store"],
          url: "view-pharm-order",
          orderIndex: 4,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit Store",
          slug: "edit-pharmacy",
          navParentId: navParentsMap["Pharmacy Store"],
          url: "edit-pharmstore",
          orderIndex: 5,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Delete Store",
          slug: "delete-pharmacy-store",
          navParentId: navParentsMap["Pharmacy Store"],
          url: "delete-pharmstore",
          orderIndex: 6,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          id: uuidv4(),
          name: "Create Shelf",
          slug: "create-shelf",
          navParentId: navParentsMap["General Store"],
          url: "create-gen-store",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Shelf",
          slug: "view-shelf",
          navParentId: navParentsMap["General Store"],
          url: "view-gen-store",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Place Order",
          slug: "raise-general-order",
          navParentId: navParentsMap["General Store"],
          url: "create-genstore-order",
          orderIndex: 3,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Order",
          slug: "view-general-order",
          navParentId: navParentsMap["General Store"],
          url: "view-gen-order",
          orderIndex: 4,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit shelf",
          slug: "edit-general-store",
          navParentId: navParentsMap["General Store"],
          url: "edit-genstore",
          orderIndex: 5,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Delete Shelf",
          slug: "delete-shelf",
          navParentId: navParentsMap["General Store"],
          url: "delete-genstore",
          orderIndex: 6,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(), //Department Store
          name: "Create",
          slug: "create-department-store",
          navParentId: navParentsMap["Department Store"],
          url: "create-dept-store",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View All",
          slug: "department-store-products",
          navParentId: navParentsMap["Department Store"],
          url: "view-deptstore-prod",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Raw materials",
          slug: "view-store-raw",
          navParentId: navParentsMap["Department Store"],
          url: "view-deptstore-raw",
          orderIndex: 3,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Place Order",
          slug: "place-store-order",
          navParentId: navParentsMap["Department Store"],
          url: "create-deptstore-order",
          orderIndex: 4,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Orders",
          slug: "view-dept-orders",
          navParentId: navParentsMap["Department Store"],
          url: "view-deptstore-order",
          orderIndex: 5,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit Store",
          slug: "edit-dept-store",
          navParentId: navParentsMap["Department Store"],
          url: "edit-deptstore",
          orderIndex: 6,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Delete Store",
          slug: "delete-dept-store",
          navParentId: navParentsMap["Department Store"],
          url: "delete-deptstore",
          orderIndex: 7,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(), //Tickets
          name: "Raise Auth to Give and collect Cash",
          slug: "auth-to-give-and-collect-cash",
          navParentId: navParentsMap["Tickets"],
          url: "cash-ticket",
          orderIndex: 1,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "ATG&CC",
          slug: "cash-authority",
          navParentId: navParentsMap["Tickets"],
          url: "view-cash-ticket",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Raise Auth to Weigh",
          slug: "auth-to-weigh",
          navParentId: navParentsMap["Tickets"],
          url: "raise-auth-weigh",
          orderIndex: 7,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "ATW",
          slug: "authority-to-weigh",
          navParentId: navParentsMap["Tickets"],
          url: "view-all-auth-weigh",
          orderIndex: 8,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Raise LPO",
          slug: "raise-lpo",
          navParentId: navParentsMap["Tickets"],
          url: "raise-lpo",
          orderIndex: 3,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "L.P.O",
          slug: "l.p.o",
          navParentId: navParentsMap["Tickets"],
          url: "view-lpo",
          orderIndex: 4,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Raise Auth to collect from store",
          slug: "auth-to-collect-from-store",
          navParentId: navParentsMap["Tickets"],
          url: "raise-store-collection",
          orderIndex: 5,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "ATCFGS",
          slug: "store-authority",
          navParentId: navParentsMap["Tickets"],
          url: "view-store-auth",
          orderIndex: 6,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Recieve Cash Ticket",
          slug: "recieve-cash-authority",
          navParentId: navParentsMap["Cashier"],
          url: "recieve-cash-ticket",
          orderIndex: 3,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      
        {
          id: uuidv4(),
          name: "Generate Invoice",
          slug: "generate-invoice",
          navParentId: navParentsMap["Customers"],
          url: "create-invoice",
          orderIndex: 7,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Invoice",
          slug: "invoice",
          navParentId: navParentsMap["Receipts"],
          url: "get-all-invoice",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Generate waybill",
          slug: "generate-waybill",
          navParentId: navParentsMap["Receipts"],
          url: "create-waybill",
          orderIndex: 2,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Waybill",
          slug: "waybill",
          navParentId: navParentsMap["Receipts"],
          url: "get-all-waybill",
          orderIndex: 3,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Generate GatePass",
          slug: "generate-gatepass",
          navParentId: navParentsMap["Receipts"],
          url: "create-gatepass",
          orderIndex: 4,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Gate Pass Note",
          slug: "gate-pass-note",
          navParentId: navParentsMap["Receipts"],
          url: "get-all-gatepass",
          orderIndex: 5,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Create vehicle Dispatch",
          slug: "create-vehicle-dispatch",
          navParentId: navParentsMap["Receipts"],
          url: "create-vehicle-dispatch",
          orderIndex: 6,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Vehicle Dispatch Note",
          slug: "vehicle-dispatch-note",
          navParentId: navParentsMap["Receipts"],
          url: "get-all-vehicle-dispatch",
          orderIndex: 7,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Create Role",
          slug: "create-role",
          navParentId: navParentsMap["Admins"],
          url: "create-role",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Edit Role",
          slug: "edit-role",
          navParentId: navParentsMap["Admins"],
          url: "edit-role",
          orderIndex: 2,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Roles",
          slug: "view-roles",
          navParentId: navParentsMap["Admins"],
          url: "get-roles",
          orderIndex: 3,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Create Admin",
          slug: "create-admin",
          navParentId: navParentsMap["Admins"],
          url: "reg-staff",
          orderIndex: 4,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View Admins",
          slug: "view-admins",
          navParentId: navParentsMap["Admins"],
          url: "all-staff",
          orderIndex: 5,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Suspended Admins",
          slug: "suspended-admins",
          navParentId: navParentsMap["Admins"],
          url: "suspended-staff",
          orderIndex: 6,
          isNav: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Add",
          slug: "add-department",
          navParentId: navParentsMap["Department"],
          url: "create-department",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "View",
          slug: "view-departments",
          navParentId: navParentsMap["Department"],
          url: "view-department",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Cash Management",
          slug: "cash-management",
          navParentId: navParentsMap["Cashier"],
          url: "create-cashier-book",
          orderIndex: 1,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuidv4(),
          name: "Cash Ledger",
          slug: "cash-ledger",
          navParentId: navParentsMap["Cashier"],
          url: "cashier-ledger",
          orderIndex: 2,
          isNav: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface: QueryInterface) {
    await queryInterface.bulkDelete("Permissions", {}, {});
  },
};
