import { QueryInterface, DataTypes } from "sequelize";
import { v4 as uuidv4 } from 'uuid';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
    await queryInterface.bulkInsert("NavParents", [
      {
        id: uuidv4(), 
        name: "Account Book",
        iconUrl: "fa-hat",
        slug: "account-book",
        orderIndex: 1,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),

      },
      {
        id: uuidv4(),
        name: "Customers",
        iconUrl: "fa-users",
        slug: "customers",
        orderIndex: 2,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),

      },
      {
        id: uuidv4(), 
        name: "Suppliers",
        iconUrl: "fa-truck-loading",
        slug: "suppliers",
        orderIndex: 3,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),

      },
      {
        id: uuidv4() ,
        name: "Products",
        iconUrl: "fa-box-open",
        slug: "products",
        orderIndex: 4,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),

      },
      {
        id: uuidv4(),
        name: "Admins",
        iconUrl: "fa-user-shield",
        slug: "admins",
        orderIndex: 5,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),

      },
      {
        id: uuidv4(),
        name: "General Store",
        iconUrl: "fa-store",
        slug: "general-store",
        orderIndex: 6,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        name: "Department Store",
        iconUrl: "fa-store-alt",
        slug: "department-store",
        orderIndex: 7,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        name: "Department Ledger",
        iconUrl: "fa-book",
        slug: "department-ledger",
        orderIndex: 8,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        name: "Raise Ticket",
        iconUrl: "fa-ticket-alt",
        slug: "raise-ticket",
        orderIndex: 10,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        name: "Pharmacy Store",
        iconUrl: "fa-pills",
        slug: "pharmacy-store",
        orderIndex: 11,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        name: "Department",
        iconUrl: "fa-buildings",
        slug: "department",
        orderIndex: 12,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        name: "Tickets",
        iconUrl: "fa-tags",
        slug: "tickets",
        orderIndex: 13,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),

      },
      {
        id: uuidv4(),
        name: "Cashier",
        iconUrl: "fa-money-bill-wave",
        slug: "cash-managment",
        orderIndex: 14,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        name: "Accounting",
        iconUrl: "fa-calculator",
        slug: "accounting",
        orderIndex: 15,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        name: "Weigh Brigde",
        iconUrl: "fa-balance-scale",
        slug: "weighing-operations",
        orderIndex: 16,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        name: "Report",
        iconUrl: "fa-file-alt",
        slug: "report",
        orderIndex: 17,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id:uuidv4() ,
        name: "Notification",
        iconUrl: "fa-bell",
        slug: "notification",
        orderIndex: 18,
        isNav: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface: QueryInterface) {
    await queryInterface.bulkDelete("NavParents", {}, {});
  },
};
